name: Docker Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Debug - Print SSH connection details
      run: |
        echo "Attempting to connect to: ${{ secrets.SERVER_HOST }}"
        echo "Using username: ${{ secrets.SERVER_USERNAME }}"
        echo "SSH key is set: ${{ secrets.SERVER_SSH_KEY != '' }}"

    - name: Test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 300s
        script: echo "SSH connection successful"
      
    - name: Build Docker image and deploy
      run: |
        cd PROJECT_PATH
        git pull origin main
        docker build -t PROJECT_NAME:latest .
        cd PROJECT_PATH
        docker compose -f PROJECT_NAME.yaml -p PROJECT_NAME up -d PROJECT_NAME